releases:
  - name: rediscart
    chart: charts/redis
    values:
      - values/redis-values.yaml
      - appReplicas: "1"

  - name: emailservice
    chart: charts/microservice
    values:
      - values/email-service-values.yaml