apiVersion: apps/v1
kind: Deployment
metadata:
  name: job
spec:
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - name: job
        image: "busybox"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

